name: Workflow Dispatch Tests

on:
  # Manually dispatched workflow action
  workflow_dispatch:
    inputs:
      runner:
        description: 'Self hosted gh runner'
        required: true

jobs:
  workflow-dispatch-tests:
    runs-on: [self-hosted, linux, x64, "${{ inputs.runner }}"]
    steps:
      - name: Sleep for an hour to allow time for the runner to crash.
        run: |
          sleep 3600
